### ISSUE TITLE
求助：本地无法启动运行，报错 500--Servlet.service() for servlet [dispatcherServlet] in context with path [/renren-fast] threw exception [Filtered request failed.] with root cause

### ISSUE THREAD

**Issue by sdy8181** [zyanycall/stressTestPlatform#69]
log：
020-05-07 15:43:00.340 ERROR 13160 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/renren-fast] threw exception [Filtered request failed.] with root cause

java.lang.IllegalArgumentException: There is no configured chain under the name/key [].
	at org.apache.shiro.web.filter.mgt.DefaultFilterChainManager.proxy(DefaultFilterChainManager.java:322)
	at org.apache.shiro.web.filter.mgt.PathMatchingFilterChainResolver.getChain(PathMatchingFilterChainResolver.java:126)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.getExecutionChain(AbstractShiroFilter.java:415)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:448)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

谢谢

**Comment by zyanycall** [comment]
没遇到过这种问题，抱歉啊……建议看看tomcat的配置吧。

**Comment by huyuwei1996** [comment]
@zyanycall 今天我也有出现。
本地运行，访问http://localhost:8080/renren-fast/控制台就会有这个报错
访问http://localhost:8080/renren-fast/index.html可以正常进入性能测试平台

**Comment by sdy8181** [comment]
> @zyanycall 今天我也有出现。
> 本地运行，访问http://localhost:8080/renren-fast/
> 控制台就会有这个报错
> 访问http://localhost:8080/renren-fast/index.html
> 可以正常进入性能测试平台

哇，确实，你给的链接可以访问，直接入renren-fast这样的根访问就不行，谢谢。

@zyanycall 大佬，这个和url路由有关系吗？  有没有这个项目结构比较详细的说明，准备项目中仔细实践一下，感谢分享

**Comment by huyuwei1996** [comment]
我也是想了解，估计还是得自己去先学习下Springboot就能看得懂了。
感觉和路由有关，或者/的重定向，但不知道去哪改，/renren-fast/不能自己跳到/renren-fast/index.html

**Comment by smooth00** [comment]
> 我也是想了解，估计还是得自己去先学习下Springboot就能看得懂了。
> 感觉和路由有关，或者/的重定向，但不知道去哪改，/renren-fast/不能自己跳到/renren-fast/index.html

和路由无关，和shiro有关

**Comment by sdy8181** [comment]
> > 我也是想了解，估计还是得自己去先学习下Springboot就能看得懂了。
> > 感觉和路由有关，或者/的重定向，但不知道去哪改，/renren-fast/不能自己跳到/renren-fast/index.html
> 
> 和路由无关，和shiro有关

你也出现这个问题了？怎么修改的，3x
